#!/bin/bash

clear

echo "BUILDING..."
cmake ./doomify -B ./build

echo "COMPILING..."
cmake --build ./build

echo "POPULATING PALETTES FOLDER..."
mkdir -p ./bin/palettes/
cp ./doomify/palettes/* ./bin/palettes/

echo "ATTEMPTING TO RUN DOOMIFY..."
cd bin
./doomify

cd ..
